### ISSUE TITLE
double press and clicks

### ISSUE THREAD

**Issue by Switchcrafter** [dmadison/HID_Buttons#7]
I pushed your mouse and keyboard examples to a SAMD21 board.   Every single click [Keyboard] sends "cc"  or mouse example does double click each time.  Not even sure where to start...

**Comment by dmadison** [comment]
What is your hardware setup?

The examples are barebones and are just to show how to use the library. If you're having issues with the input being pressed multiple times you probably need to debounce it.

**Comment by Switchcrafter** [comment]
Yep.  Adding a debounce fixed it
